// frontend/src/App.jsx
import { useState, useEffect, useCallback } from 'react'
import MedicamentoList from './MedicamentoList' 
import UploadFile from './upload'
import Auth from './Auth'
import Navbar from './components/Navbar'
import Hero from './components/Hero'
import AdminPanel from './components/AdminPanel'
import { apiService } from './services/api'
import './App.css'
import Mapa from './Mapa';

function App() {
  const [user, setUser] = useState(null)
  
  const [medicamentos, setMedicamentos] = useState([])
  const [listaEstabelecimentos, setListaEstabelecimentos] = useState([])
  const [loading, setLoading] = useState(false)
  const [page, setPage] = useState(1)
  const [totalPages, setTotalPages] = useState(1)

  const [filtros, setFiltros] = useState({
    q: '',
    catmat: '',
    estabelecimento: ''
  })

  useEffect(() => {
    const savedUser = localStorage.getItem("usuario");
    if (savedUser) {
      const parsedUser = JSON.parse(savedUser);
      // Proteção contra cache da versão antiga (antes dos múltiplos perfis)
      if (!parsedUser.perfis) {
        localStorage.removeItem("usuario");
        localStorage.removeItem("token");
        window.location.reload();
      } else {
        setUser(parsedUser);
      }
    }
  }, []);

  useEffect(() => {
    if (!user) return;
    const carregarEstabelecimentos = async () => {
      try {
        const dados = await apiService.getEstabelecimentos();
        setListaEstabelecimentos(dados);
      } catch (error) {
        console.error(error);
      }
    };
    carregarEstabelecimentos();
  }, [user]);

  const fetchMedicamentos = useCallback(async () => {
    if (!user) return;
    setLoading(true)
    try {
      const data = await apiService.getMedicamentos({ page, ...filtros });
      setMedicamentos(data.items || []) 
      setTotalPages(data.pages || 1)
    } catch (error) {
      console.error(error)
    } finally {
      setLoading(false)
    }
  }, [page, filtros, user]);

  useEffect(() => {
    fetchMedicamentos()
  }, [fetchMedicamentos])

  const handleFilterChange = (novoFiltro) => {
    setFiltros(prev => ({ ...prev, ...novoFiltro }))
    setPage(1)
  }

  const handleUploadSuccess = () => {
    fetchMedicamentos();
  }

  const handleLogout = () => {
    apiService.logout();
    setUser(null);
  }

  if (!user) {
    return <Auth onLogin={setUser} />;
  }

  return (
    <div className="app-wrapper bg-light min-vh-100">
      <Navbar user={user} onLogout={handleLogout} />
      <Hero />
      
      <main className="container pb-5">
        <Mapa />
        
        {user.perfis.includes("administrador") && (
          <div className="mt-4">
            <UploadFile onSuccess={handleUploadSuccess} />
            <div className="mt-4">
              <AdminPanel />
            </div>
          </div>
        )}
        
        <MedicamentoList 
          medicamentos={medicamentos} 
          listaEstabelecimentos={listaEstabelecimentos}
          filtros={filtros}
          onFilterChange={handleFilterChange}
          page={page}
          setPage={setPage}
          totalPages={totalPages}
          loading={loading}
        />
      </main>
    </div>
  )
}

export default App

// frontend_vue/src/App.vue
<template>
  <!-- Se não estiver logado -->
  <Auth
    v-if="!user"
    @login="handleLogin"
  />

  <!-- Se estiver logado -->
  <div
    v-else
    class="app-wrapper bg-light min-vh-100"
  >
    <Navbar
      :user="user"
      @logout="handleLogout"
    />

    <Hero />

    <main class="container pb-5">
      <Mapa />

      <!-- Área exclusiva do administrador -->
      <div
        v-if="user.perfis.includes('administrador')"
        class="mt-4"
      >
        <Upload @success="handleUploadSuccess" />

        <div class="mt-4">
          <AdminPanel />
        </div>
      </div>

      <MedicamentoList
        :medicamentos="medicamentos"
        :lista-estabelecimentos="listaEstabelecimentos"
        :filtros="filtros"
        :page="page"
        :total-pages="totalPages"
        :loading="loading"
        @filter-change="handleFilterChange"
        @update:page="page = $event"
      />
    </main>
  </div>
</template>

<script setup>
import { ref, reactive, watch, onMounted } from 'vue'

import Auth from './components/Auth.vue'
import Navbar from './components/Navbar.vue'
import Hero from './components/Hero.vue'
import Mapa from './components/Mapa.vue'
import Upload from './components/Upload.vue'
import AdminPanel from './components/AdminPanel.vue'
import MedicamentoList from './components/MedicamentoList.vue'

import { apiService } from './services/api'

import './App.css'


// ==========================
// USUÁRIO
// ==========================

const user = ref(null)


// ==========================
// MEDICAMENTOS
// ==========================

const medicamentos = ref([])

const listaEstabelecimentos = ref([])

const loading = ref(false)

const page = ref(1)

const totalPages = ref(1)


// ==========================
// FILTROS
// ==========================

const filtros = reactive({
  q: '',
  catmat: '',
  estabelecimento: ''
})


// ==========================
// LOGIN SALVO
// ==========================

onMounted(() => {
  const savedUser = localStorage.getItem('usuario')

  if (savedUser) {
    const parsedUser = JSON.parse(savedUser)

    // Proteção contra versão antiga
    // anterior aos múltiplos perfis
    if (!parsedUser.perfis) {
      localStorage.removeItem('usuario')
      localStorage.removeItem('token')

      window.location.reload()
      return
    }

    user.value = parsedUser
  }
})


// ==========================
// CARREGAR ESTABELECIMENTOS
// ==========================

const carregarEstabelecimentos = async () => {
  if (!user.value) return

  try {
    const dados = await apiService.getEstabelecimentos()

    listaEstabelecimentos.value = dados
  } catch (error) {
    console.error('Erro ao carregar estabelecimentos:', error)
  }
}


// ==========================
// CARREGAR MEDICAMENTOS
// ==========================

const fetchMedicamentos = async () => {
  if (!user.value) return

  loading.value = true

  try {
    const data = await apiService.getMedicamentos({
      page: page.value,
      q: filtros.q,
      catmat: filtros.catmat,
      estabelecimento: filtros.estabelecimento
    })

    medicamentos.value = data.items || []

    totalPages.value = data.pages || 1
  } catch (error) {
    console.error('Erro ao carregar medicamentos:', error)
  } finally {
    loading.value = false
  }
}


// ==========================
// LOGIN
// ==========================

const handleLogin = (usuario) => {
  user.value = usuario
}


// ==========================
// LOGOUT
// ==========================

const handleLogout = () => {
  apiService.logout()

  user.value = null

  medicamentos.value = []

  listaEstabelecimentos.value = []
}


// ==========================
// ALTERAÇÃO DOS FILTROS
// ==========================

const handleFilterChange = (novoFiltro) => {
  Object.assign(filtros, novoFiltro)

  page.value = 1
}


// ==========================
// UPLOAD CONCLUÍDO
// ==========================

const handleUploadSuccess = () => {
  fetchMedicamentos()
}


// ==========================
// OBSERVADORES
// ==========================

// Quando usuário logar
watch(user, async (novoUsuario) => {
  if (!novoUsuario) return

  await carregarEstabelecimentos()

  await fetchMedicamentos()
})


// Quando mudar página ou filtro
watch(
  [
    page,
    () => filtros.q,
    () => filtros.catmat,
    () => filtros.estabelecimento
  ],
  () => {
    fetchMedicamentos()
  }
)
</script>
