// frontend_vue/src/components/Upload.vue
<template>
  <div class="card border-0 shadow-sm rounded-4">
    <div class="card-body p-4">

      <h5 class="fw-bold mb-3">
        <i class="bi bi-file-earmark-arrow-up me-2"></i>
        Atualizar estoque
      </h5>

      <p class="text-muted small">
        Selecione a planilha Excel contendo os dados atualizados
        do estoque de medicamentos.
      </p>

      <div class="mb-3">
        <input
          ref="fileInput"
          type="file"
          class="form-control"
          accept=".xlsx,.xls"
          @change="handleFileChange"
        />
      </div>

      <!-- Arquivo selecionado -->
      <div
        v-if="arquivo"
        class="alert alert-light border d-flex align-items-center"
      >
        <i class="bi bi-file-earmark-excel me-2"></i>

        <span class="small">
          {{ arquivo.name }}
        </span>
      </div>

      <!-- Mensagem -->
      <div
        v-if="mensagem"
        class="alert"
        :class="erro ? 'alert-danger' : 'alert-success'"
      >
        {{ mensagem }}
      </div>

      <button
        type="button"
        class="btn text-white rounded-pill px-4 fw-bold"
        style="background-color: var(--achei-teal)"
        :disabled="!arquivo || loading"
        @click="handleUpload"
      >
        <span
          v-if="loading"
          class="spinner-border spinner-border-sm me-2"
        ></span>

        {{ loading ? 'Enviando...' : 'Enviar planilha' }}
      </button>

    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { apiService } from '../services/api'

const emit = defineEmits(['success'])

const arquivo = ref(null)
const loading = ref(false)

const mensagem = ref('')
const erro = ref(false)

const fileInput = ref(null)


// ==========================
// SELECIONAR ARQUIVO
// ==========================

const handleFileChange = (event) => {
  arquivo.value = event.target.files[0]

  mensagem.value = ''
  erro.value = false
}


// ==========================
// ENVIAR ARQUIVO
// ==========================

const handleUpload = async () => {
  if (!arquivo.value) {
    mensagem.value = 'Selecione uma planilha primeiro.'
    erro.value = true
    return
  }

  loading.value = true

  mensagem.value = ''
  erro.value = false

  try {
    const response = await apiService.uploadFile(
      arquivo.value
    )

    mensagem.value =
      response.message || 'Planilha enviada com sucesso!'

    erro.value = false

    // Limpa arquivo selecionado
    arquivo.value = null

    if (fileInput.value) {
      fileInput.value.value = ''
    }

    // Avisa App.vue que o estoque foi atualizado
    emit('success')

  } catch (error) {
    mensagem.value =
      error.message || 'Erro ao enviar a planilha.'

    erro.value = true

  } finally {
    loading.value = false
  }
}
</script>

// frontend/src/upload.jsx
import { useState, useRef } from "react"
import { apiService } from "./services/api";

const UploadFile = ({ onSuccess }) => {
  const [file, setFile] = useState(null)
  const [loading, setLoading] = useState(false)
  const fileInputRef = useRef(null)

  const onFileChange = (e) => {
    setFile(e.target.files[0])
  }

  const onSubmit = async (e) => {
    e.preventDefault();
    if (!file) return alert("Por favor, selecione um arquivo primeiro!");

    setLoading(true);
    try {
      const response = await apiService.uploadFile(file);
      alert(response.message || "Arquivo enviado com sucesso!");
      
      // Limpa os estados
      setFile(null);
      if (fileInputRef.current) fileInputRef.current.value = "";
      
      // Chama o hook de sucesso para recarregar os dados na tabela
      if (onSuccess) onSuccess(); 
    } catch (error) {
      alert(error.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="card border-0 shadow-sm rounded-4 p-4 mb-4" style={{ backgroundColor: "#eef8fa" }}>
      <div className="d-flex justify-content-between align-items-center mb-3">
        <h5 className="mb-0 fw-bold" style={{ color: "var(--achei-blue)" }}>
          <i className="bi bi-cloud-arrow-up me-2"></i>
          Atualização de Estoque
        </h5>
        <span className="badge bg-warning text-dark">Painel do Administrador</span>
      </div>
      
      <p className="text-muted small mb-3">
        Selecione a planilha Excel mais recente (.xls ou .xlsx) contendo os dados dos estoques de todas as unidades.
      </p>

      <form onSubmit={onSubmit} className="d-flex align-items-center gap-3">
        <div className="flex-grow-1">
          <input 
            type="file" 
            className="form-control" 
            id="file" 
            onChange={onFileChange} 
            ref={fileInputRef}
            accept=".xls,.xlsx"
          />
        </div>
        <button 
          type="submit" 
          className="btn text-white px-4 fw-bold" 
          style={{ backgroundColor: "var(--achei-teal)" }}
          disabled={loading || !file}
        >
          {loading ? (
            <><span className="spinner-border spinner-border-sm me-2" role="status" aria-hidden="true"></span>Enviando...</>
          ) : (
            "Enviar Planilha"
          )}
        </button>
      </form>
    </div>
  )
}

export default UploadFile
